language: scala

scala:
- 2.10.7
- 2.11.12
- 2.12.6
- 2.13.0-M5

jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"

script:
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" &&
          "${TRAVIS_BRANCH}" == "master" &&
          $(cat version.sbt) =~ "-SNAPSHOT"
    ]]; then
      sbt ++${TRAVIS_SCALA_VERSION} validate publish ;
    else
      sbt ++${TRAVIS_SCALA_VERSION} validate ;
    fi

sudo: false

env:
  global:
  - secure: M21Qw4W77YIqTEr5yv1Q5S48ioO9RykUsC5qVxvUb6rpAgYTn4ZRV7K2QLP+ZfwK9OswOgl0Oo6XFVbLchea0jfDXe0a8gytEN6Eed9QhtDWE4Z1wrRR+RLzDTrUjVjaU0vujJPeTOvlRZgJ5b7nMVmg2IsCv1fSkk8omDehWVay1pJcV2ibSVGl/fPfQJwYnNn8ICjLxbVEZZA/tMpR/qzQUhJ14lZk/dK1blFK+Bw6DeRnVKE/ytDqufnc1fgEVkj+se4f0NWEdMdQmsBA8aUKGXAr1HrGGlJLynEjtAqEWF38SWoAMfzDxAXAesDmGgzlRiFkMKTPaguDBLsx2rcciowsX6Qp+ennf0a+xJJEu/tNyxK+VG1cIkobg5Q8rFz8rMSv/Dpm91L1D/q3ySdmAhkwTPXa8dXTLJfzOWHxIesprhopMTN9c6K/kQUhFVqm5VpiKRkKVkYbKIdEaINlyx5wR4oldpEJPtkYjRSpX8yQXHdr/uybgs/t6h91pY1fgONM1OiDh2FGr4hkaN3fNvAZnzC6MyjlmzzlOP3Mk72DyhgQNQnEOqxBNyHfiKpy+JFSnMjd5KAbuVuZRLsuUkdycEXfDNulG09eV0u7T+qTUeEg85KQBHYMxHggkb58k0tjuSnZicHZQZCuQYKs4xesZAN9qhsbnPKHVD8=
  - secure: PTStlCWk8p3RhHEF3YIvJ5LUlfJjSfS/qYMBJ/shcPrvL8aPzifakZGv8iW3vecr4dCPIydZvw3wONgsj+8rSBimKbo9yL8TxVS5awDWHhP/m9IuVV8rEBnqeC5lsBTpg7n/Ctb/6cK/qsyNfat6YFkycRSDuG/QJNLXxTG1DUPIYG2Hrsei64E/U0PkKBVh2KwxPpc/vsYBNsWlAWWQG9DInTmhzcNTHo5r4pfwzeAZ6Z/bpsudK7WI9DlTDyMJSnXp6eF1BIBhjg7apJQfS/McgxKjuB3tqqV2jG4ygzTqSLWGd5qB5C8v8OwLBG+AHDuDHsEqroCAd1QSwNdTUUV5J0V0epqnetebIi44rbNnnjr5zxHn6v0gyh1VNaSHGa073lKlWwsI+L0x8w+yUFs4EmWicUr3MH9Tf+A0zTzggmPnBCxndEcJ4Qt2gqhnOYf/9YlDJP0HBUW3tWMiGzd1LKaFphiDCchSlaJKEqdVncMBFexg7U9ksmsqp7W/75ePhbzc0lRtzppoiDhKvBRJ6rlqkfV3e7gd+tC1kmwKqotsAZYUCN5BAR3YMO8UO4lkVTkjYN1Qxw3Kqr5my4VwftfdWkAq+Llr5eQDCaFOngcIMU1cFPz873bZsZqjhrXHPY94Yvlby/xv8jTYJF5PYTLSRE/0g1ifBoJebOc=

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/13693154b9f6e97b90f4
